# Why 80 columns still? Because I can fit two 80-column-wide editor panes
# side by side on my smallest screen at my preferred font size, but I can't
# if you go even a little wider.
max_width = 80
newline_style = "Unix"
